# This is a basic workflow to help you get started with Actions

name: Demo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        agente: ['windows-latests', 'ubuntu-latests','macos-latests']
    # The type of runner that the job will run on
    runs-on: ${{matrix.agente}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions@setup-dotnet@v2
      with:
        dotonet-version: 3.1.102
    - name: Build project
      run: dotnet build -c Release
    - name: Build project
      run: dotnet test -c Release
